### ISSUE TITLE
Caching issues with trailing slashes in URLs

### ISSUE THREAD

**Issue by pfinners** [ProtoSchool/protoschool.github.io#530] opened 2020-08-16 00:34 UTC
Unfortunately there is a bug in the first page of lesson 1. If the incorrect option is selected once even selecting the correct option will not allow progression to the next Q.  This happens even if the browser is closed and link reopened. See attached photo:
![AB0D28E6-5960-4C8C-888E-C312286A35C0](https://user-images.githubusercontent.com/69703918/90323962-1a7d2700-dfac-11ea-8510-b847dfc38e71.jpeg)

**Comment by terichadbourne** [comment] 2020-08-16 00:43
Thank you so much for reporting this bug! I’ll plan to take a look on Monday and see if I can find the source. Looks to me like it’s happening on the other lessons as well.

**Comment by terichadbourne** [comment] 2020-08-18 15:18
Hi @pfinners! Digging into this more deeply and I'm unable to reproduce in an incognito browser, which leads me to believe the bug is related to our caching mechanisms. A couple of questions for you... 

What browser are you using?

When this happened, had you visited the tutorial previously, or was it your first time? 

Do you recall if you had clicked `right answer ->  wrong answer  -> right answer` or just `wrong answer -> right answer` ? 

If you're familiar with how to find localStorage in the Application tab of your browser inspector, would you mind sharing a screenshot? 

I received this one from someone having a similar issue:

![image](https://user-images.githubusercontent.com/19171465/90531392-053b0080-e144-11ea-997f-8bf4c749e5e5.png)

**Comment by pfinners** [comment] 2020-08-18 15:49
Hi, This happened in the safari browser to 4 independent people. It happened me when I clicked the incorrect answer first and then selected the correct answer next.  It happened the first time I opened the browser. I?m not familiar with how to share browser inspector details for safari. If you have an iPhone with a safari browser try the above and I think you will be able to reproduce the issue. Best regards,Pete On Wed, 19 Aug 2020 at 01:18, Teri Chadbourne <notifications@github.com> wrote:Hi @pfinners! Digging into this more deeply and I'm unable to reproduce in an incognito browser, which leads me to believe the bug is related to our caching mechanisms. A couple of questions for you...What browser are you using?When this happened, had you visited the tutorial previously, or was it your first time?Do you recall if you had clicked right answer ->  wrong answer  -> right answer or just wrong answer -> right answer ?If you're familiar with how to find localStorage in the Application tab of your browser inspector, would you mind sharing a screenshot?I received this one from someone having a similar issue:?You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by terichadbourne** [comment] 2020-08-18 15:51
Thanks for the additional detail, @pfinners!

**Comment by terichadbourne** [comment] 2020-08-18 16:30
**Debugging Notes**

- **Cypress doesn't fail multiple choice tests locally.** In the `main` branch locally, which should match what's currently published, there are no failures in tests. The test for multiple choice lessons includes using one sample lesson and clicking the right answer, then the wrong answers, then the right answers again to ensure the next button appears both times for the right answer. It had been running this with Anatomy of a CID as an example but I switched it to the first Verifying Storage on Filecoin lesson and it still passed. This suggests the failure is happening with something that's different between the Cypress experience and the user's experience. While Cypress only tests on Chrome currently, the problem has been reported by live users both in Chrome (Ian) and Safari (Pete), so it's not necessarily browser-specific. 

- **Works correctly in incognito Chrome with fresh localStorage at https://proto.school/verifying-storage-on-filecoin/01 (no trailing slash, as it is when you navigate there from our tutorial listings).**  Opening the live site from an incognito Chrome browser on a Mac, I can't reproduce the error. The next button appears correctly both on first and later selection of correct answer. Sample of localStorage: 
![image](https://user-images.githubusercontent.com/19171465/90537056-dd9b6680-e14a-11ea-9d37-876301b022a0.png)

- **Broken in incognito Chrome with cleared localStorage at https://proto.school/verifying-storage-on-filecoin/01/ (trailing slash, which is added if you refresh the page)** - can never get the next button to appear, regardless of what order I choose right and wrong answers in. Note that in this case the `cached` value in localStorage appends a slash and the `passed` one doesn't. 

![image](https://user-images.githubusercontent.com/19171465/90537410-4b479280-e14b-11ea-97c1-5cf23ccbf51f.png)

The only way I can get to the version without the trailing slash seems to be within the app itself, so by clicking from the tutorial page listing to the landing page to the first lesson, or using the next button to get from one lesson to the next. Even if I intentionally go to the slashless version via my URL bar, it immediately redirects me to trailing slash version that doesn't work. 

If I've been to the same page on both slashed and slashless versions, I end up with one version of the slashless `passed/verifying-storage-on-filecoin/01`, and the date of passing correctly updates when I select the right answer, even though when I'm on the slashed version I can see neither the green feedback nor the enabled next button. 

![image](https://user-images.githubusercontent.com/19171465/90539177-81861180-e14d-11ea-8d59-8f26f7fbe926.png)

However, there are two versions of the `cached` data, with and without the slash, one of which changes when I click around on the slashed page and one on the unslashed page: 

![image](https://user-images.githubusercontent.com/19171465/90539381-bdb97200-e14d-11ea-99c4-79d7faf4f318.png)

I believe @zebateira had to make some changes to trailing slashes related to our recent switch from hash routing to history routing, so I assume the bug was introduced recently. I'll proceed on the theory that this is the source of the problem. I need to dig further to confirm whether the same problem is affected lessons of other types and just hasn't been reported yet. 

@pfinners While I work on this, I suspect that you and your colleagues will have a successful experience if you start from the [tutorial landing page ](https://proto.school/verifying-storage-on-filecoin) and then click to get to lesson 1, rather than dropping into lesson 1 directly via URL. Please let me know if that helps, and I'll keep you posted when I get this fixed in the code.

**Comment by terichadbourne** [comment] 2020-08-18 16:56
We've indeed broken every lesson type, though each in a different way: 

**Multiple choice:** 
- Without trailing slash, works correctly
- With trailing slash, correctly updates `passed` date when correct but **generates a second cached entry (different history based on URL)**,  **can't see green feedback on correct answer and next button remains disabled**

**Text only:** 
- With trailing slash, works correctly and proceeds to next lesson
- Without trailing slash, **next button is still available but leads to a 404 page** rather than the next lesson

**Code (with or without file upload):** 
- Without trailing slash: works correctly, caches code, passes with correct submission, proceeds to next lesson
- With trailing slash: **caches code with trailing slash (creating two versions of cached code)**, correcly updates passed value but **doesn't show next button or success message** when correct code is submitted

I'm not sure of the best long term solution between caching with or without slashes, but since historical passed records have no slashes, but I don't want to mess around with the routing itself, so we need to accommodate in a way that keep functionality regardless of whether the URL has a trailing slash. For now I'll try to make everything in localStorage cache without them and @zebateira can advise on the best long term solution when he's back from vacation.

**Closed** 2020-08-18 19:09 UTC
Labels: P0 - Critical, bug, lesson-feedback

**Comment by terichadbourne** [comment] 2020-08-19 13:21
@pfinners We pushed a fix to this issue. Thanks again for reporting it! If you continue to have any issues, please let us know.

**Comment by pfinners** [comment] 2020-08-19 15:24
Thanks.  Great it?s fixed On Wed, 19 Aug 2020 at 23:22, Teri Chadbourne <notifications@github.com> wrote:@pfinners We pushed a fix to this issue. Thanks again for reporting it! If you continue to have any issues, please let us know.?You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
