### ISSUE TITLE
Bug: Submitting when making no changes to default code shows no output

### ISSUE THREAD

**Issue by mikeal** [ProtoSchool/protoschool.github.io#132] opened 2019-01-15 20:43 UTC
**Describe the bug**

Bring up a lesson, hit submit and don't type anything new in the code box.

**Comment by terichadbourne** [comment] 2019-01-16 20:59
@mikeal This bug is caused by the method I used to clear error messages (simply prevent them from displaying) when you click to reset the code. An error message is currently only displayed when there's cached code (the code isn't in its default state). At present, the error message (now out of date) returns as soon as you type the first character after hitting "reset code." A success message disappears completely until you submit again. As I fix this, what should we consider the ideal sticking-around time for a success or failure message? 

Option 1: It's visible until you start editing the code in any way, at which point it disappears. It only reappears when you hit submit again, at which point it's a new error/success message. 

Option 2: It stays until you hit submit again so that you can refer to it (for example, see that it was recommending you return until you've had time to add "return" to your code. When you submit again, it's replaced by the new success/failure message. 

Option 3: It stays until you hit submit again so that you can refer to it, UNLESS you click "reset code," in which case it goes away until you hit submit and get a new one.

I think I'd lean toward Option 3, which is what I was attempting to implement earlier.

**Comment by mikeal** [comment] 2019-01-17 20:57
I like Option 3 as well. Sometimes, even as you're adding code you want to refer back to the error you had previously gotten.

**Comment by fsdiogo** [comment] 2019-08-16 16:47
This has been fixed in https://github.com/ProtoSchool/protoschool.github.io/pull/267.

**Closed by fsdiogo** 2019-08-16 16:47 UTC
Labels: bug
