### ISSUE TITLE
Bug: Links to filtered tutorial results redirect to tutorials page 

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#674] opened 2021-05-28 20:20 UTC
This is a bug with the filtered by course tutorial listings (eg https://proto.school/tutorials?course=ipld), NOT the course pages

To reproduce: 
Go to https://proto.school/tutorials and select a course from the dropdown
After it loads, copy the URL, such as https://proto.school/tutorials?course=ipfs 
Paste the URL and try to load
it redirects to https://proto.school/tutorials

**Comment by zebateira** [comment] 2021-05-31 10:47
Very weird.
Can't reproduce this locally. And now it seems it redirects to the filecoin tutorials list instead of simply removing the query parameters? So weird.

Looking into this with the Fleek team since I believe it is a weird caching issue on their CDN? If you use a forward slash at the end of the path it works. Example: https://proto.school/tutorials/?course=ipfs

**Comment by zebateira** [comment] 2021-06-01 14:14
Working now 👍 
The fleek is now working on a global fix internally but it's now working for ProtoSchool, so closing this.

**Closed by zebateira** 2021-06-01 14:14 UTC
Labels: bug
