### ISSUE TITLE
Bug: IPLD Explorer not loading

### ISSUE THREAD

**Issue by Frijol** [ProtoSchool/protoschool.github.io#164] opened 2019-02-25 18:39 UTC
**Describe the bug**
Endless load screen including in Incognito

**Does this bug apply to a specific lesson or tutorial, or does it appear to be sitewide?**
Linked from successful completion of Basics 1: https://ipfs.io/ipfs/QmYJETQ15RAnKXoJxqpXzcvQ2DuQA35UHwJBTjTPCSs9Ky/#/explore/zdpuApm55Qv2zRxb3KKjVUxhQSw2r4a7jeiDV7163yCQnfivy

**Expected behavior**
Not sure yet what IPLD Explorer is supposed to look like but probably something should load!

**Screenshots**
![screen shot 2019-02-25 at 10 36 19 am](https://user-images.githubusercontent.com/454690/53360029-566c8a00-38e9-11e9-99e9-edadf959146c.png)

**To reproduce**
Complete https://proto.school/#/basics/01 exercise & click on the View in IPLD.. link

**Desktop (please complete the following information):**
- OS: Mac OSX
- Browser Chrome
- Version whatsmybrowser.org/b/HGLEACT

**Additional context**

**Comment by terichadbourne** [comment] 2019-02-25 19:44
This is a duplicate of #125 but helps us know that the issue applies across multiple lessons. I believe the issue is actually with IPLD Explorer, not ProtoSchool but am awaiting a chance to talk further with @olizilla.

**Comment by olizilla** [comment] 2019-03-05 17:49
From waht I can see, IPLD explor is loading, but cannot discover the content on the network. My guess is that we need to update the version of js-ipfs that is bundled with proto.school. will test it out and PR.

**Comment by mikeal** [comment] 2019-03-05 18:02
When his originally was reported we were having issues with the seed nodes, have those issues been resolved?

**Comment by olizilla** [comment] 2019-03-05 18:04
From what I can see right now, IPLD explor is loading, but cannot discover the content on the network. My guess is that we need to update the version of js-ipfs that is bundled with proto.school. will test it out and PR.

Also we're linking to an old snapshot of ipld explorer, which should still work fine, but may as well be updated to point to https://explore.ipld.io

**Comment by terichadbourne** [comment] 2019-03-05 18:25
Thanks for looking into this @olizilla. Happy to accept a PR, but if you need my help or want to look at anything together, just let me know.

**Closed** 2019-03-07 18:17 UTC
Labels: bug
