### ISSUE TITLE
Provide better error message when wrong CID returned (Basics lesson 2)

### ISSUE THREAD

**Issue by lanzafame** [ProtoSchool/protoschool.github.io#120] opened 2019-01-08 03:03 UTC
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**
https://proto.school/#/basics/02

**What's confusing about this lesson?**
The error message returned when the wrong cid is returned. It isn't readable (data is return as bytes), and the message also get truncated.
See: 
![1546913603](https://user-images.githubusercontent.com/5924712/50807040-d3956d00-1344-11e9-9f8e-d7ba22e3ac70.png)

**Comment by mikeal** [comment] 2019-01-14 19:57
@terichadbourne should we create a new issue detailing the *fix* for this problem, or should we rename the issue here and start detailing the fix in-line?

**Comment by mikeal** [comment] 2019-01-15 18:00
In *most* of the tutorials we have code that checks if there is a CID and if it is incorrect it produces a different error message that just not returning a CID at all, or returning some other incorrect value. The problem is, we didn't update this after the CID API changes, it used to show the base encoded string for the CID but now it just tries to print the CID in several places. We just need to go in and clean up those error messages to print the base encoded CID.

**Comment by terichadbourne** [comment] 2019-12-10 21:54
I just tested this output again and it's no longer truncated on the live site but does still return data in the format shown above (objects, not strings). 

Just submitted a potential fix in #328 but would love feedback as to whether it's a reasonable approach before proceeding.

**Comment by terichadbourne** [comment] 2020-02-18 22:33
previously closed via #328

**Closed by terichadbourne** 2020-02-18 22:33 UTC
